// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Dv_orkJ79keKoYd1rRwG8GkwJAx97cs',
    appId: '1:178869717437:web:e85911d8044ad3ad3e6ad4',
    messagingSenderId: '178869717437',
    projectId: 'kasentra-7e9b2',
    authDomain: 'kasentra-7e9b2.firebaseapp.com',
    storageBucket: 'kasentra-7e9b2.firebasestorage.app',
    measurementId: 'G-63EDXHM8KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Dv_orkJ79keKoYd1rRwG8GkwJAx97cs',
    appId: '1:178869717437:android:placeholder',
    messagingSenderId: '178869717437',
    projectId: 'kasentra-7e9b2',
    storageBucket: 'kasentra-7e9b2.firebasestorage.app',
  );

  static const FirebaseOptions iOS = FirebaseOptions(
    apiKey: 'AIzaSyC2Dv_orkJ79keKoYd1rRwG8GkwJAx97cs',
    appId: '1:178869717437:ios:placeholder',
    messagingSenderId: '178869717437',
    projectId: 'kasentra-7e9b2',
    storageBucket: 'kasentra-7e9b2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Dv_orkJ79keKoYd1rRwG8GkwJAx97cs',
    appId: '1:178869717437:macos:placeholder',
    messagingSenderId: '178869717437',
    projectId: 'kasentra-7e9b2',
    storageBucket: 'kasentra-7e9b2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Dv_orkJ79keKoYd1rRwG8GkwJAx97cs',
    appId: '1:178869717437:windows:placeholder',
    messagingSenderId: '178869717437',
    projectId: 'kasentra-7e9b2',
    storageBucket: 'kasentra-7e9b2.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC2Dv_orkJ79keKoYd1rRwG8GkwJAx97cs',
    appId: '1:178869717437:linux:placeholder',
    messagingSenderId: '178869717437',
    projectId: 'kasentra-7e9b2',
    storageBucket: 'kasentra-7e9b2.firebasestorage.app',
  );

  // Alias for iOS to maintain consistency
  static const FirebaseOptions ios = iOS;
}
